### ISSUE TITLE
Motion sensor lacks of lightlevel and dark property

### ISSUE THREAD

**Issue by tim-hellhake** [mozilla-iot/philips-hue-adapter#43] opened 2019-04-22 20:35 UTC
The motion sensor delivers 3 values: `lightlevel`, `dark` and `daylight`.
Currently only `daylight` is exposed as property.

**Comment by freaktechnik** [comment] 2019-04-22 21:09
I believe this is a dupe of https://github.com/mozilla-iot/philips-hue-adapter/issues/25 btw. All the values are exposed, they are just exposed as three things.

**Closed** 2019-04-30 15:22 UTC
